// Script to seed initial data into MongoDB
// Run: node seedData.js (from backend directory)

import mongoose from "mongoose";
import dotenv from "dotenv";
import User from "./models/User.js";
import MenuItem from "./models/MenuItem.js";
import Order from "./models/Order.js";

dotenv.config();

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected for seeding");
  } catch (error) {
    console.error("❌ MongoDB connection failed:", error.message);
    process.exit(1);
  }
};

const seedDatabase = async () => {
  try {
    // Clear existing data
    await User.deleteMany({});
    await MenuItem.deleteMany({});
    await Order.deleteMany({});
    console.log("🧹 Cleared existing data");

    // Seed Users
    const users = await User.insertMany([
      {
        name: "John Doe",
        email: "user@example.com",
        password: "password123",
        role: "user",
      },
      {
        name: "Jane Smith",
        email: "jane@example.com",
        password: "password123",
        role: "user",
      },
      {
        name: "Admin User",
        email: "admin@example.com",
        password: "admin123",
        role: "admin",
      },
    ]);
    console.log("✅ Users seeded:", users.length);

    // Seed Menu Items - 50 items from different restaurants
    const menuItems = await MenuItem.insertMany([
      // Pizza Hut - 5 items
      {
        name: "Margherita Pizza",
        description: "Classic pizza with tomato, mozzarella, and fresh basil",
        price: 299,
        category: "Pizza",
        restaurant: "Pizza Hut",
        image: "https://images.unsplash.com/photo-1579751626658-0e754007371d?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Pepperoni Pizza",
        description: "Delicious pizza with pepperoni and mozzarella cheese",
        price: 349,
        category: "Pizza",
        restaurant: "Pizza Hut",
        image: "https://images.unsplash.com/photo-1628840042765-356cda07f4ee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Veggie Pizza",
        description: "Fresh vegetables on a crispy crust with mozzarella",
        price: 279,
        category: "Pizza",
        restaurant: "Pizza Hut",
        image: "https://images.unsplash.com/photo-1511689915989-24d7b1295f0e?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "BBQ Chicken Pizza",
        description: "Grilled chicken with BBQ sauce and crispy crust",
        price: 379,
        category: "Pizza",
        restaurant: "Pizza Hut",
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Supreme Pizza",
        description: "Loaded with pepperoni, sausage, vegetables, and cheese",
        price: 399,
        category: "Pizza",
        restaurant: "Pizza Hut",
        image: "https://images.unsplash.com/photo-1605970900711-dd91ba3c3203?w=500&h=500&fit=crop",
        availability: true,
      },

      // Domino's - 5 items
      {
        name: "Garlic Bread Pizza",
        description: "Crispy garlic bread with cheese topping",
        price: 259,
        category: "Pizza",
        restaurant: "Domino's",
        image: "https://images.unsplash.com/photo-1573821663912-569905455552?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Spicy Chicken Pizza",
        description: "Spicy grilled chicken with hot sauce",
        price: 349,
        category: "Pizza",
        restaurant: "Domino's",
        image: "https://images.unsplash.com/photo-1537619798693-c87d5ceb0f2b?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Paneer Tikka Pizza",
        description: "Indian style paneer tikka on pizza base",
        price: 329,
        category: "Pizza",
        restaurant: "Domino's",
        image: "https://images.unsplash.com/photo-1564693565519-55a9140ea217?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Cheese Lovers Pizza",
        description: "Extra cheese and white sauce pizza",
        price: 379,
        category: "Pizza",
        restaurant: "Domino's",
        image: "https://images.unsplash.com/photo-1557003552-169f50b2b4e9?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Nonveg Pizza",
        description: "Chicken, beef, and sausage combination",
        price: 429,
        category: "Pizza",
        restaurant: "Domino's",
        image: "https://images.unsplash.com/photo-1585238341710-4913d3a374a3?w=500&h=500&fit=crop",
        availability: true,
      },

      // Burger King - 5 items
      {
        name: "Classic Cheeseburger",
        description: "Juicy beef patty with cheddar cheese and fresh toppings",
        price: 249,
        category: "Burger",
        restaurant: "Burger King",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Bacon Burger",
        description: "Delicious burger with crispy bacon and special sauce",
        price: 279,
        category: "Burger",
        restaurant: "Burger King",
        image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Double Burger",
        description: "Two beef patties with double cheese and vegetables",
        price: 329,
        category: "Burger",
        restaurant: "Burger King",
        image: "https://images.unsplash.com/photo-1585238341710-4913d3a374a3?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Spicy Chicken Burger",
        description: "Crispy spicy chicken patty with mayo and lettuce",
        price: 269,
        category: "Burger",
        restaurant: "Burger King",
        image: "https://images.unsplash.com/photo-1562547256-52ce0521b723?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Mushroom Swiss Burger",
        description: "Grilled mushrooms with swiss cheese on beef patty",
        price: 299,
        category: "Burger",
        restaurant: "Burger King",
        image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=500&h=500&fit=crop",
        availability: true,
      },

      // McDonald's - 5 items
      {
        name: "Big Mac",
        description: "Two all beef patties, special sauce, lettuce, cheese",
        price: 239,
        category: "Burger",
        restaurant: "McDonald's",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Quarter Pounder",
        description: "Quarter pound beef patty with bacon and cheese",
        price: 289,
        category: "Burger",
        restaurant: "McDonald's",
        image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "McChicken Burger",
        description: "Crispy chicken patty with mayo and pickles",
        price: 219,
        category: "Burger",
        restaurant: "McDonald's",
        image: "https://images.unsplash.com/photo-1562547256-52ce0521b723?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Double Cheeseburger",
        description: "Two beef patties and double american cheese",
        price: 249,
        category: "Burger",
        restaurant: "McDonald's",
        image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Crispy Chicken Burger",
        description: "Golden fried chicken with lettuce and tomato",
        price: 239,
        category: "Burger",
        restaurant: "McDonald's",
        image: "https://images.unsplash.com/photo-1570521944256-178ffde95538?w=500&h=500&fit=crop",
        availability: true,
      },

      // Coca Cola - 5 items
      {
        name: "Coca Cola",
        description: "Refreshing cold cola beverage",
        price: 89,
        category: "Drinks",
        restaurant: "Coca Cola",
        image: "https://images.unsplash.com/photo-1554866585-e4897c5ca4e0?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Sprite",
        description: "Crisp lemon-lime flavored soda",
        price: 89,
        category: "Drinks",
        restaurant: "Coca Cola",
        image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Fanta Orange",
        description: "Bright orange flavored fruit drink",
        price: 89,
        category: "Drinks",
        restaurant: "Coca Cola",
        image: "https://images.unsplash.com/photo-1592190881346-7e1fa15c1ef9?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Minute Maid",
        description: "Orange juice beverage",
        price: 129,
        category: "Drinks",
        restaurant: "Coca Cola",
        image: "https://images.unsplash.com/photo-1600271886742-f049cd1f89f6?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Iced Tea",
        description: "Chilled refreshing iced tea",
        price: 79,
        category: "Drinks",
        restaurant: "Coca Cola",
        image: "https://images.unsplash.com/photo-1556742212-5b321f3c261d?w=500&h=500&fit=crop",
        availability: true,
      },

      // Starbucks - 5 items
      {
        name: "Caramel Frappuccino",
        description: "Cold caramel blended coffee drink",
        price: 189,
        category: "Drinks",
        restaurant: "Starbucks",
        image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Vanilla Latte",
        description: "Smooth espresso with steamed milk",
        price: 159,
        category: "Drinks",
        restaurant: "Starbucks",
        image: "https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Iced Americano",
        description: "Bold iced coffee with water",
        price: 129,
        category: "Drinks",
        restaurant: "Starbucks",
        image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Matcha Green Tea Latte",
        description: "Japanese matcha with steamed milk",
        price: 169,
        category: "Drinks",
        restaurant: "Starbucks",
        image: "https://images.unsplash.com/photo-1597318777845-53c31e65eaec?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Cold Brew Coffee",
        description: "Smooth cold brewed coffee",
        price: 149,
        category: "Drinks",
        restaurant: "Starbucks",
        image: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=500&h=500&fit=crop",
        availability: true,
      },

      // The Cheesecake Factory - 5 items
      {
        name: "Chocolate Cake",
        description: "Rich chocolate cake with creamy frosting",
        price: 189,
        category: "Dessert",
        restaurant: "The Cheesecake Factory",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Classic Cheesecake",
        description: "Creamy New York style cheesecake",
        price: 219,
        category: "Dessert",
        restaurant: "The Cheesecake Factory",
        image: "https://images.unsplash.com/photo-1533134242443-742894d33e7f?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Strawberry Cheesecake",
        description: "Fresh strawberry topped cheesecake",
        price: 249,
        category: "Dessert",
        restaurant: "The Cheesecake Factory",
        image: "https://images.unsplash.com/photo-1613395877297-413debb16688?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chocolate Lava Cake",
        description: "Warm molten chocolate cake with ice cream",
        price: 219,
        category: "Dessert",
        restaurant: "The Cheesecake Factory",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Tiramisu",
        description: "Italian layered coffee dessert",
        price: 189,
        category: "Dessert",
        restaurant: "The Cheesecake Factory",
        image: "https://images.unsplash.com/photo-1571115764595-644467f3f5d1?w=500&h=500&fit=crop",
        availability: true,
      },

      // Cold Stone - 5 items
      {
        name: "Vanilla Ice Cream",
        description: "Classic vanilla ice cream",
        price: 159,
        category: "Dessert",
        restaurant: "Cold Stone",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e0b0?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chocolate Ice Cream",
        description: "Rich chocolate ice cream",
        price: 159,
        category: "Dessert",
        restaurant: "Cold Stone",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e0b0?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Strawberry Shortcake",
        description: "Fresh strawberries with whipped cream",
        price: 189,
        category: "Dessert",
        restaurant: "Cold Stone",
        image: "https://images.unsplash.com/photo-1585080353235-19b4e50d1f2b?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Cookie Dough Sundae",
        description: "Ice cream with cookie dough and chocolate",
        price: 219,
        category: "Dessert",
        restaurant: "Cold Stone",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e0b0?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Brownie Sundae",
        description: "Warm brownie with ice cream and toppings",
        price: 219,
        category: "Dessert",
        restaurant: "Cold Stone",
        image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&h=500&fit=crop",
        availability: true,
      },

      // Panera Bread - 5 items
      {
        name: "Caesar Salad",
        description: "Fresh romaine lettuce with parmesan and croutons",
        price: 249,
        category: "Salad",
        restaurant: "Panera Bread",
        image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Greek Salad",
        description: "Fresh vegetables with feta cheese and olives",
        price: 279,
        category: "Salad",
        restaurant: "Panera Bread",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Caprese Salad",
        description: "Tomatoes, mozzarella, basil with balsamic",
        price: 249,
        category: "Salad",
        restaurant: "Panera Bread",
        image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Spinach Salad",
        description: "Fresh spinach with strawberries and almonds",
        price: 249,
        category: "Salad",
        restaurant: "Panera Bread",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Cobb Salad",
        description: "Chicken, bacon, avocado, blue cheese salad",
        price: 309,
        category: "Salad",
        restaurant: "Panera Bread",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop",
        availability: true,
      },

      // Olive Garden - 5 items
      {
        name: "Fettuccine Alfredo",
        description: "Creamy pasta with parmesan cheese sauce",
        price: 349,
        category: "Pasta",
        restaurant: "Olive Garden",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Spaghetti Marinara",
        description: "Spaghetti with classic tomato marinara sauce",
        price: 299,
        category: "Pasta",
        restaurant: "Olive Garden",
        image: "https://images.unsplash.com/photo-1612874742237-415c69f18978?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Lasagna Classico",
        description: "Layers of pasta, meat, and cheese",
        price: 379,
        category: "Pasta",
        restaurant: "Olive Garden",
        image: "https://images.unsplash.com/photo-1587927231902-2a87aab428d2?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Ravioli Ricotta",
        description: "Cheese ravioli with creamy sauce",
        price: 329,
        category: "Pasta",
        restaurant: "Olive Garden",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chicken Parmesan",
        description: "Breaded chicken with marinara and cheese",
        price: 399,
        category: "Pasta",
        restaurant: "Olive Garden",
        image: "https://images.unsplash.com/photo-1587927231902-2a87aab428d2?w=500&h=500&fit=crop",
        availability: true,
      },
      
      // Indian Restaurants - Ongole
      // Spice Route - 5 items
      {
        name: "Hyderabadi Biryani",
        description: "Aromatic basmati rice cooked with tender chicken and exotic spices",
        price: 249,
        category: "Biryani",
        restaurant: "Spice Route - Ongole",
        image: "https://images.unsplash.com/photo-1585566299430-a10e96b2c6c3?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Mutton Biryani",
        description: "Slow-cooked mutton with fragrant rice and yogurt marinade",
        price: 289,
        category: "Biryani",
        restaurant: "Spice Route - Ongole",
        image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Paneer Butter Masala",
        description: "Soft paneer cubes in creamy tomato-based sauce with butter and cream",
        price: 229,
        category: "Curry",
        restaurant: "Spice Route - Ongole",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Tandoori Chicken",
        description: "Marinated chicken grilled in clay oven with aromatic spices",
        price: 269,
        category: "Tandoor",
        restaurant: "Spice Route - Ongole",
        image: "https://images.unsplash.com/photo-1588050551726-bc1e7a01cc63?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Butter Naan",
        description: "Soft Indian bread brushed with butter, cooked in traditional tandoor",
        price: 49,
        category: "Bread",
        restaurant: "Spice Route - Ongole",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },

      // South Indian Restaurant - Ongole
      {
        name: "Masala Dosa",
        description: "Crispy rice and lentil crepe filled with spiced potatoes and onions",
        price: 129,
        category: "South Indian",
        restaurant: "South Indian Palace - Ongole",
        image: "https://images.unsplash.com/photo-1585864299869-592a18302993?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Sambar Idli",
        description: "Steamed rice cake served with spicy sambar and coconut chutney",
        price: 99,
        category: "South Indian",
        restaurant: "South Indian Palace - Ongole",
        image: "https://images.unsplash.com/photo-1585864299861-351cce4344ce?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chikhalwali Uttapam",
        description: "Thick rice pancake topped with tomatoes, onions, and chilies",
        price: 119,
        category: "South Indian",
        restaurant: "South Indian Palace - Ongole",
        image: "https://images.unsplash.com/photo-1585864299961-1894f3ce4b36?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Medu Vada",
        description: "Crispy fried lentil donuts, served with sambar and chutney",
        price: 89,
        category: "South Indian",
        restaurant: "South Indian Palace - Ongole",
        image: "https://images.unsplash.com/photo-1585864299869-592a18302993?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Coconut Chutney",
        description: "Fresh coconut ground with green chilies and spices",
        price: 29,
        category: "Chutney",
        restaurant: "South Indian Palace - Ongole",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd1b6be?w=500&h=500&fit=crop",
        availability: true,
      },

      // Andhra Kitchen - Ongole
      {
        name: "Gongura Chicken",
        description: "Tender chicken cooked in traditional Andhra-style with sorrel leaves",
        price: 239,
        category: "Curry",
        restaurant: "Andhra Kitchen - Ongole",
        image: "https://images.unsplash.com/photo-1603894752066-a12e89ba0a09?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Natukodi Koora",
        description: "Authentic country chicken curry with Andhra spices",
        price: 249,
        category: "Curry",
        restaurant: "Andhra Kitchen - Ongole",
        image: "https://images.unsplash.com/photo-1588050551726-bc1e7a01cc63?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Pesarattu",
        description: "Savory green moong dal crepe, crispy and delicious",
        price: 109,
        category: "South Indian",
        restaurant: "Andhra Kitchen - Ongole",
        image: "https://images.unsplash.com/photo-1585864299869-592a18302993?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Andehra Dal",
        description: "Traditional lentil curry with cumin and dried chilies",
        price: 119,
        category: "Curry",
        restaurant: "Andhra Kitchen - Ongole",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chapati",
        description: "Soft Indian wheat bread made fresh on order",
        price: 39,
        category: "Bread",
        restaurant: "Andhra Kitchen - Ongole",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },

      // Fort House - Ongole
      {
        name: "Samosa (4 pieces)",
        description: "Crispy fried pastry filled with spiced potatoes and peas",
        price: 79,
        category: "Appetizer",
        restaurant: "Fort House - Ongole",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Paneer Tikka",
        description: "Marinated paneer pieces grilled with peppers and onions",
        price: 169,
        category: "Appetizer",
        restaurant: "Fort House - Ongole",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd1b6be?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chicken Seekh Kebab",
        description: "Minced chicken mixed with spices, grilled on skewers",
        price: 189,
        category: "Appetizer",
        restaurant: "Fort House - Ongole",
        image: "https://images.unsplash.com/photo-1588050551726-bc1e7a01cc63?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Lakhnavi Biryani",
        description: "Lucknow-style biryani with layered rice and tender chicken",
        price: 259,
        category: "Biryani",
        restaurant: "Fort House - Ongole",
        image: "https://images.unsplash.com/photo-1585566299430-a10e96b2c6c3?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Shahi Tukda",
        description: "Fried bread soaked in sweet milk, topped with dry fruits",
        price: 129,
        category: "Dessert",
        restaurant: "Fort House - Ongole",
        image: "https://images.unsplash.com/photo-1585080353235-19b4e50d1f2b?w=500&h=500&fit=crop",
        availability: true,
      },

      // Ongole Rasoi - Ongole
      {
        name: "Vegetable Fried Rice",
        description: "Indo-Chinese style fried rice with mixed vegetables",
        price: 149,
        category: "Rice",
        restaurant: "Ongole Rasoi - Ongole",
        image: "https://images.unsplash.com/photo-1585867741671-4dae925505ee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chicken Fried Rice",
        description: "Aromatic fried rice with tender chicken pieces",
        price: 169,
        category: "Rice",
        restaurant: "Ongole Rasoi - Ongole",
        image: "https://images.unsplash.com/photo-1585867741805-f6a82f40d69d?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chow Mein",
        description: "Stir-fried noodles with vegetables and soy sauce",
        price: 129,
        category: "Noodles",
        restaurant: "Ongole Rasoi - Ongole",
        image: "https://images.unsplash.com/photo-1609340881563-430f63602d4b?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Paneer Manchurian",
        description: "Fried paneer cubes in tangy and spicy sauce",
        price: 179,
        category: "Indo-Chinese",
        restaurant: "Ongole Rasoi - Ongole",
        image: "https://images.unsplash.com/photo-1585167741805-f6a82f40d69d?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Gobi Manchurian",
        description: "Crispy fried cauliflower in savory Indo-Chinese sauce",
        price: 149,
        category: "Indo-Chinese",
        restaurant: "Ongole Rasoi - Ongole",
        image: "https://images.unsplash.com/photo-1609340881563-430f63602d4b?w=500&h=500&fit=crop",
        availability: true,
      },

      // Rishi Dhaba - Ongole
      {
        name: "Chicken Masala",
        description: "Tender chicken in aromatic tomato-based masala curry",
        price: 229,
        category: "Curry",
        restaurant: "Rishi Dhaba - Ongole",
        image: "https://images.unsplash.com/photo-1603894752066-a12e89ba0a09?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Dal Makhani",
        description: "Creamy lentil curry cooked overnight with butter and cream",
        price: 169,
        category: "Curry",
        restaurant: "Rishi Dhaba - Ongole",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Rajma Chawal",
        description: "Kidney beans curry served with steamed basmati rice",
        price: 139,
        category: "Rice",
        restaurant: "Rishi Dhaba - Ongole",
        image: "https://images.unsplash.com/photo-1585867741671-4dae925505ee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Bhindi Fry",
        description: "Crispy okra cooked with onions and spices",
        price: 109,
        category: "Vegetable",
        restaurant: "Rishi Dhaba - Ongole",
        image: "https://images.unsplash.com/photo-1609340881563-430f63602d4b?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Aloo Gobi",
        description: "Potatoes and cauliflower cooked in traditional Indian spices",
        price: 99,
        category: "Vegetable",
        restaurant: "Rishi Dhaba - Ongole",
        image: "https://images.unsplash.com/photo-1609340881563-430f63602d4b?w=500&h=500&fit=crop",
        availability: true,
      },

      // Kaveri Grand - Ongole
      {
        name: "Chicken Pulao",
        description: "Fragrant rice cooked with tender chicken and spices",
        price: 189,
        category: "Rice",
        restaurant: "Kaveri Grand - Ongole",
        image: "https://images.unsplash.com/photo-1585867741805-f6a82f40d69d?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Mixed Veg Pulao",
        description: "Mixed vegetables with basmati rice and aromatic spices",
        price: 149,
        category: "Rice",
        restaurant: "Kaveri Grand - Ongole",
        image: "https://images.unsplash.com/photo-1585867741671-4dae925505ee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Biryani Special",
        description: "House special biryani with meat and fragrant basmati",
        price: 249,
        category: "Biryani",
        restaurant: "Kaveri Grand - Ongole",
        image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Egg Fried Rice",
        description: "Fried rice with scrambled eggs and vegetables",
        price: 129,
        category: "Rice",
        restaurant: "Kaveri Grand - Ongole",
        image: "https://images.unsplash.com/photo-1585867741805-f6a82f40d69d?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Tandoori Fish",
        description: "Fresh fish marinated and grilled in tandoor",
        price: 279,
        category: "Tandoor",
        restaurant: "Kaveri Grand - Ongole",
        image: "https://images.unsplash.com/photo-1612521534637-d4b341e55f4e?w=500&h=500&fit=crop",
        availability: true,
      },

      // Lakshmi's Pulkapoint - Ongole
      {
        name: "Butter Pulka",
        description: "Soft wheat bread puffed and brushed with butter",
        price: 49,
        category: "Bread",
        restaurant: "Lakshmi's Pulkapoint - Ongole",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Masala Pulka",
        description: "Spicy pulka with cumin and chili powder",
        price: 59,
        category: "Bread",
        restaurant: "Lakshmi's Pulkapoint - Ongole",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Aloo Parantha",
        description: "Thin bread stuffed with spiced potatoes",
        price: 69,
        category: "Bread",
        restaurant: "Lakshmi's Pulkapoint - Ongole",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Paneer Parantha",
        description: "Flaky bread stuffed with cottage cheese",
        price: 79,
        category: "Bread",
        restaurant: "Lakshmi's Pulkapoint - Ongole",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Methi Parantha",
        description: "Whole wheat bread with fresh fenugreek leaves",
        price: 69,
        category: "Bread",
        restaurant: "Lakshmi's Pulkapoint - Ongole",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },

      // Hotel Grand - Nellore
      {
        name: "Garlic Naan",
        description: "Soft naan with roasted garlic and herbs",
        price: 59,
        category: "Bread",
        restaurant: "Hotel Grand - Nellore",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chole Bhature",
        description: "Fluffy fried bread served with spiced chickpeas",
        price: 149,
        category: "Bread",
        restaurant: "Hotel Grand - Nellore",
        image: "https://images.unsplash.com/photo-1585707860885-9e41d4d8fdee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Shahi Paneer",
        description: "Paneer in rich and creamy royal sauce",
        price: 199,
        category: "Curry",
        restaurant: "Hotel Grand - Nellore",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Lamb Rogan Josh",
        description: "Tender lamb in aromatic spiced tomato gravy",
        price: 249,
        category: "Curry",
        restaurant: "Hotel Grand - Nellore",
        image: "https://images.unsplash.com/photo-1603894752066-a12e89ba0a09?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Gulab Jamun",
        description: "Soft dough balls in sweet sugar syrup",
        price: 79,
        category: "Dessert",
        restaurant: "Hotel Grand - Nellore",
        image: "https://images.unsplash.com/photo-1585080353235-19b4e50d1f2b?w=500&h=500&fit=crop",
        availability: true,
      },

      // Tirupati Palace - Tirupati
      {
        name: "Tirupati Special Dosa",
        description: "Crispy dosa with special tirupati chutney",
        price: 139,
        category: "South Indian",
        restaurant: "Tirupati Palace - Tirupati",
        image: "https://images.unsplash.com/photo-1585864299869-592a18302993?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Pongal",
        description: "Rice and moong dal cooked with pepper and cashews",
        price: 99,
        category: "South Indian",
        restaurant: "Tirupati Palace - Tirupati",
        image: "https://images.unsplash.com/photo-1585867741671-4dae925505ee?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Appam",
        description: "Soft fermented rice pancake with coconut",
        price: 89,
        category: "South Indian",
        restaurant: "Tirupati Palace - Tirupati",
        image: "https://images.unsplash.com/photo-1585864299961-1894f3ce4b36?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Vegetable Kurma",
        description: "Mixed vegetables in creamy coconut-based gravy",
        price: 129,
        category: "Curry",
        restaurant: "Tirupati Palace - Tirupati",
        image: "https://images.unsplash.com/photo-1609340881563-430f63602d4b?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Payasam",
        description: "Sweet rice pudding with jaggery and dry fruits",
        price: 99,
        category: "Dessert",
        restaurant: "Tirupati Palace - Tirupati",
        image: "https://images.unsplash.com/photo-1585080353235-19b4e50d1f2b?w=500&h=500&fit=crop",
        availability: true,
      },

      // Krishna Villa - Ongole
      {
        name: "Vegetable Dum Biryani",
        description: "Vegetables and rice cooked in sealed handi",
        price: 179,
        category: "Biryani",
        restaurant: "Krishna Villa - Ongole",
        image: "https://images.unsplash.com/photo-1585566299430-a10e96b2c6c3?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Chicken Chettinad",
        description: "Spicy chicken with traditional chettinad masala",
        price: 219,
        category: "Curry",
        restaurant: "Krishna Villa - Ongole",
        image: "https://images.unsplash.com/photo-1603894752066-a12e89ba0a09?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Goat Biryani",
        description: "Tender goat meat with basmati rice and spices",
        price: 279,
        category: "Biryani",
        restaurant: "Krishna Villa - Ongole",
        image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Mint Rice",
        description: "Fragrant rice cooked with fresh mint leaves",
        price: 139,
        category: "Rice",
        restaurant: "Krishna Villa - Ongole",
        image: "https://images.unsplash.com/photo-1585867741805-f6a82f40d69d?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Kheer",
        description: "Rice pudding cooked with milk and cardamom",
        price: 89,
        category: "Dessert",
        restaurant: "Krishna Villa - Ongole",
        image: "https://images.unsplash.com/photo-1585080353235-19b4e50d1f2b?w=500&h=500&fit=crop",
        availability: true,
      },

      // Nellore Biryani House - Nellore
      {
        name: "Nellore Biryani",
        description: "Famous local biryani with special spice blend",
        price: 249,
        category: "Biryani",
        restaurant: "Nellore Biryani House - Nellore",
        image: "https://images.unsplash.com/photo-1585566299430-a10e96b2c6c3?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Prawn Biryani",
        description: "Fresh prawns with aromatic basmati rice",
        price: 299,
        category: "Biryani",
        restaurant: "Nellore Biryani House - Nellore",
        image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Fish Curry",
        description: "Fresh fish in coconut-based curry",
        price: 199,
        category: "Curry",
        restaurant: "Nellore Biryani House - Nellore",
        image: "https://images.unsplash.com/photo-1612521534637-d4b341e55f4e?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Dalcha Rice",
        description: "Lentil and meat rice preparation",
        price: 169,
        category: "Rice",
        restaurant: "Nellore Biryani House - Nellore",
        image: "https://images.unsplash.com/photo-1585867741805-f6a82f40d69d?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Halim",
        description: "Slow-cooked meat and lentils preparation",
        price: 129,
        category: "Curry",
        restaurant: "Nellore Biryani House - Nellore",
        image: "https://images.unsplash.com/photo-1603894752066-a12e89ba0a09?w=500&h=500&fit=crop",
        availability: true,
      },

      // Maharaja Restaurant - Ongole
      {
        name: "Handi Chicken",
        description: "Chicken cooked in sealed clay pot with spices",
        price: 229,
        category: "Curry",
        restaurant: "Maharaja Restaurant - Ongole",
        image: "https://images.unsplash.com/photo-1588050551726-bc1e7a01cc63?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Paya Curry",
        description: "Slow-cooked goat leg curry, tender and spicy",
        price: 189,
        category: "Curry",
        restaurant: "Maharaja Restaurant - Ongole",
        image: "https://images.unsplash.com/photo-1603894752066-a12e89ba0a09?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Boti Kabab",
        description: "Marinated meat pieces grilled on charcoal",
        price: 199,
        category: "Tandoor",
        restaurant: "Maharaja Restaurant - Ongole",
        image: "https://images.unsplash.com/photo-1588050551726-bc1e7a01cc63?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Nihari",
        description: "Slow-cooked meat curry with thick gravy",
        price: 189,
        category: "Curry",
        restaurant: "Maharaja Restaurant - Ongole",
        image: "https://images.unsplash.com/photo-1603894752066-a12e89ba0a09?w=500&h=500&fit=crop",
        availability: true,
      },
      {
        name: "Zarda Rice",
        description: "Sweet rice with dry fruits and saffron",
        price: 119,
        category: "Rice",
        restaurant: "Maharaja Restaurant - Ongole",
        image: "https://images.unsplash.com/photo-1585867741805-f6a82f40d69d?w=500&h=500&fit=crop",
        availability: true,
      },
    ]);
    console.log("✅ Menu items seeded:", menuItems.length);

    console.log("\n✨ Database seeded successfully!");
    console.log("\n📝 Demo Credentials:");
    console.log("   Email: user@example.com");
    console.log("   Password: password123");
    console.log("\n👨‍💼 Admin Credentials:");
    console.log("   Email: admin@example.com");
    console.log("   Password: admin123");
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
  } finally {
    await mongoose.connection.close();
    console.log("\n✅ Database connection closed");
  }
};

connectDB().then(() => seedDatabase());
